apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-preview-apps
  namespace: argocd  
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: sebquarez
        repo: gitops-cert-level-3-examples
        labels:
        - preview-ready
      requeueAfterSeconds: 10
  template:
    metadata:
      name: 'myapp-{{.branch}}'
    spec:
      source:
        repoURL: 'https://github.com/sebquarez/gitops-cert-level-3-examples.git'
        targetRevision: HEAD
        path: preview-environments/kustomize-preview-app/ 
        kustomize:
          images:
            - 'docker.io/kostiscodefresh/my-preview-app:{{.branch_slug}}'
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'preview-{{.branch_slug}}'
      syncPolicy:
        automated:
          prune: true  
        syncOptions:
        - CreateNamespace=true 